name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o linux-amd64/cicdutil -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o linux-386/cicdutil -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=5 go build -o linux-arm-5/cicdutil -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6 go build -o linux-arm-6/cicdutil -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -o linux-arm-7/cicdutil -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o linux-arm64/cicdutil -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o darwin-amd64/cicdutil -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o windows-amd64/cicdutil.exe -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -o windows-386/cicdutil.exe -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -o freebsd-amd64/cicdutil -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=freebsd GOARCH=386 go build -o freebsd-386/cicdutil -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 go build -o openbsd-amd64/cicdutil -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=openbsd GOARCH=386 go build -o openbsd-386/cicdutil -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 go build -o netbsd-amd64/cicdutil -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=netbsd GOARCH=386 go build -o netbsd-386/cicdutil -ldflags="-s -w" .
        env CGO_ENABLED=0 GOOS=dragonfly GOARCH=amd64 go build -o dragonfly-amd64/cicdutil -ldflags="-s -w" .
      
    - name: Upload artifact cicdutil-linux-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-linux-amd64
        # Directory containing files to upload
        path: linux-amd64

    - name: Upload artifact cicdutil-linux-386
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-linux-386
        # Directory containing files to upload
        path: linux-386

    - name: Upload artifact cicdutil-linux-arm-5
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-linux-arm-5
        # Directory containing files to upload
        path: linux-arm-5

    - name: Upload artifact cicdutil-linux-arm-6
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-linux-arm-6
        # Directory containing files to upload
        path: linux-arm-6

    - name: Upload artifact cicdutil-linux-arm-7
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-linux-arm-7
        # Directory containing files to upload
        path: linux-arm-7

    - name: Upload artifact cicdutil-linux-arm64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-linux-arm64
        # Directory containing files to upload
        path: linux-arm64

    - name: Upload artifact cicdutil-darwin-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-darwin-amd64
        # Directory containing files to upload
        path: darwin-amd64

    - name: Upload artifact cicdutil-dragonfly-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-dragonfly-amd64
        # Directory containing files to upload
        path: dragonfly-amd64

    - name: Upload artifact cicdutil-openbsd-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-openbsd-amd64
        # Directory containing files to upload
        path: openbsd-amd64

    - name: Upload artifact cicdutil-openbsd-386
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-openbsd-386
        # Directory containing files to upload
        path: openbsd-386

    - name: Upload artifact cicdutil-netbsd-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-netbsd-amd64
        # Directory containing files to upload
        path: netbsd-amd64

    - name: Upload artifact cicdutil-netbsd-386
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-netbsd-386
        # Directory containing files to upload
        path: netbsd-386

    - name: Upload artifact cicdutil-freebsd-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-freebsd-amd64
        # Directory containing files to upload
        path: freebsd-amd64

    - name: Upload artifact cicdutil-freebsd-386
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-freebsd-386
        # Directory containing files to upload
        path: freebsd-386

    - name: Upload artifact cicdutil-windows-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-windows-amd64
        # Directory containing files to upload
        path: windows-amd64

    - name: Upload artifact cicdutil-windows-386
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: cicdutil-windows-386
        # Directory containing files to upload
        path: windows-386

    - name: Remove old artifacts
      run: |
        sleep 180
        linux-amd64/cicdutil -p github -u missdeer -t ${{ secrets.GH_TOKEN }} -r cicdutil -k 15 -a delete